config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'site#index'
  namespace :api do
    namespace :v1 do
      post 'login', to: 'authentication#login'
      post 'signup', to: 'authentication#signup'
      delete 'logout', to: 'authentication#logout'
      resources :educations, only: ['create', 'index', 'update', 'destroy']
      resources :works, only: ['create', 'index', 'update', 'destroy']
      patch 'educations_update', to: 'educations#bulk_update'
      patch 'works_update', to: 'works#bulk_update'
      resources :skills, only: ['create', 'index', 'destroy']
      get "skills/search", to: "skills#search"
      resources :achievements, only: ['create', 'update', 'index', 'destroy']
      patch 'achievements_update', to: 'achievements#bulk_update'
      resources :projects, only: ['create', 'update', 'index', 'destroy']
      patch 'projects_update', to: 'projects#bulk_update'
      resources :users, only: ['index', 'update', 'create']
      get "users/github", to: "users#github", as: :github
      get "users/stackoverflow", to: "users#stackoverflow", as: :stackoverflow
      get "users/:id/serve", to: 'users#serve', as: :serve_photo
    end
  end

  get "/auth/facebook/callback", to: "sessions#facebook"
  get "/auth/github/callback", to: "sessions#github"
  get "/auth/stackexchange/callback", to: "sessions#stackexchange"
  get 'auth/failure', to: redirect('/')

  resources :users, only: ['index', 'new']
  get "profile/:id/", to: "users#show", as: :profile
  get "users/:id/github", to: "users#github", as: :github
  get "users/:id/stackoverflow", to: "users#stackoverflow", as: :stackoverflow
  get "users/:id/facebook", to: "users#facebook", as: :facebook
  delete 'sign_out', :to => 'sessions#destroy', as: 'logout'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Know.me</title>
    <meta name="description" content="">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="<%=image_path("favicon.png")%>">
    <link rel="icon" href="<%=image_path("favicon.png")%>" type="image/png">
    <link rel="shortcut icon" href="<%=image_path("favicon.png")%>" type="image/x-icon">
    <!-- Favicons End -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600|Open+sans:500" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="http://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.4/css/selectize.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.4/js/standalone/selectize.js"></script>
  </head>

  <body>
    <nav id="navigation" class="<% if request.path.include?('/profile/') %>d-none d-sm-block<% end %>">
        <div class="container">
            <div class="row">
                <div class="col">
                    <a href="<%=root_path%>" class="logo-brand">
                        <img src="<%=image_path("logo.png")%>">
                    </a>
                    <ul class="float-right">
                        <% if request.path.include?('/profile/') %>
                          <li >
                              <a href="javascript:void(0);" data-toggle="modal" data-target="#shareURLModal"> Share URl</a>
                          </li>
                          <li >
                          <a href="javascript:void(0);" onclick="return exportToPdf();"> Export <span class="far fa-file-pdf"></span></a>
                          </li>
                        <div class="modal fade" id="shareURLModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                          <div class="modal-dialog" role="document">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Sharing URL</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                              </div>
                              <div class="modal-body">
                                <span class="url_copied"></span>
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <button type="button" class="btn btn-primary" onclick="return copyUrl();">URL Copied!</button>
                              </div>
                            </div>
                          </div>
                        </div>
                        <% end %>
                        <% if current_user.blank? %>
                          <li >
                            <a href="<%=new_user_path%>">Sign up</a>
                          </li>
                          <li >
                            <a href="<%=users_path%>">Log in</a>
                          </li>
                        <% else %>
                          <li >
                            <%= link_to 'Profile', profile_path(id: current_user.uuid)  %>
                          </li>

                          <li >
                            <%= link_to 'Logout', api_v1_logout_path(id: current_user.id), method: :delete, confirm: "Are you sure?", title: "Logout #{current_user.email}" %>
                          </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <% flash.each do |key, value| %>
      <% if key == 'auth_token' %>
        <script type="text/javascript">localStorage.setItem("auth_token", "<%=value%>");</script>
      <% else %>
        <div class="alert-main alert alert-<%= key %>"><%= value %></div>
      <% end %>
    <% end %>

    <%= yield %>

    <%= javascript_tag do %>
      function exportToPdf(){
          window.print();
      }
    <% end %>
    <%= javascript_tag do %>

    var toCopy  = window.location.href;
    $('.url_copied').html(toCopy);


    function copyUrl(){


    var urlField = document.querySelector('.url_copied');
    //here we have used selection API to make a selection and
    //The Range interface represents a fragment of a document that can contain nodes and parts of text nodes.
    // create a Range object
    var range = document.createRange();
    // set the Node to select the "range"
    range.selectNode(urlField);
    // add the Range to the set of window selections
    window.getSelection().addRange(range);

    // execute 'copy', can't 'cut' in this case
    document.execCommand('copy');
    // console.log(urlField)
    }
  <% end %>
  </body>
</html>